version: '3'
services:
    diginext.app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
        image: diginext/laravel
        container_name: app
        restart: unless-stopped
        tty: true
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: 1000
            APP_DEBUG: true
            APP_PORT: 3000
            APP_KEY: base64:tCaWGfvJIi4tWq6IOnhYLP0EgrUR8cjfaT5Jm1FJUp4=
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: diginext_blog
            DB_USERNAME: next_admin
            DB_PASSWORD: admin123456
            SESSION_DRIVER: file
            SESSION_LIFETIME: 120
        working_dir: /var/www
        volumes:
            - ./docker/8.1/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
        depends_on:
            - mysql
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "3000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: db
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root123456
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: diginext_blog
            MYSQL_USER: next_admin
            MYSQL_PASSWORD: admin123456
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'db-mysql:/var/lib/mysql'
        networks:
            - app-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        environment:
            PMA_HOST: 'db'
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - '8081:80'
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    db-mysql:
        driver: local
